name: CI

on: [push, pull_request]

defaults:
  runs-on: ubuntu-latest

jobs:
  lint:
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  test:
    needs:
      - lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run go vet
        run: go vet $(go list ./...)
      - name: Run testing
        run: go test
  build:
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install dependencies
        run: go mod tidy
      - name: Run go build
        run: go build .
