name: Markdown

on: [push, pull_request]

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Lint Markdown files
        uses: actionshub/markdownlint@main
        with:
          filesToIgnoreRegex: LICENSE.md
